events { worker_connections 1024; }
http {
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        # Проксируем все запросы к /api на Spring Boot
        location /api/ {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
        }
    }
}